language: python
python:
  - "3.5"
  - "3.6"
  
# command to install dependencies
install:
  - pip install .
  - pip install pytest
  - pip install pytest-cov
  - pip install codecov
  
# command to run tests
script:
  - coverage run --parallel-mode --concurrency=multiprocessing --include=taskmap/taskmap.py taskmap/taskmap_test.py

after_success:
  - coverage combine && codecov
